matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: '14.15.4'
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      # addons:
      #   homebrew:
      #       packages:
      #       - rpmbuild
      #       update: true
      install: HOMEBREW_NO_AUTO_UPDATE=1 brew install rpmbuild
      script:
        - node --version
        - yarn --version
        - yarn install
        - yarn test
        - yarn run build

    - os: linux
      services: xvfb
      language: node_js
      node_js: '12'
      script:
        - node --version
        - yarn --version
        - yarn install
        - yarn test

    - os: windows
      language: node_js
      node_js: '12'
      script:
        - node --version
        - yarn --version
        - yarn install
        - yarn test  # Travis CI Windows doesn't support a GUI
        - npm run build:windows

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder




before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

notifications:
  email:
    on_success: never
    on_failure: change
