matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: '12'
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      services: xvfb
      language: node_js
      node_js: '12'

    - os: windows
      language: node_js
      node_js: '12'
      script:
        - node --version
        - npm --version
        - npm install
        - npm run build:windows

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - node --version
  - npm --version
  - npm install
  - npm test


before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

notifications:
  email:
    on_success: never
    on_failure: change
