matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: '12'
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      services: xvfb
      language: generic

  cache:
    directories:
      - node_modules
      - $HOME/.cache/electron
      - $HOME/.cache/electron-builder

  script:
    - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        export DISPLAY=:99.0
        sh -e /etc/init.d/xvfb start
        sleep 3
      fi

      node --version
      npm --version

      npm install
      npm test
  before_cache:
    - rm -rf $HOME/.cache/electron-builder/wine

  notifications:
    email:
      on_success: never
      on_failure: change
