matrix:
  fast_finish: true

platform:
  - x86
  - x64

build: off

os: unstable

branches:
  only:
    - master
    - release

skip_tags: true

environment:
  nodejs_version: "12"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
  - |
    if [[ "$PLATFORM" == "x64" ]]; then
      npx electron-builder --windows
    fi

