image: Visual Studio 2017

matrix:
  fast_finish: true

platform:
  - x86
  - x64

os: unstable

branches:
  only:
    - master
    - release

skip_tags: true

environment:
  nodejs_version: "14.15.4"

cache:
  - node_modules -> package.json
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

build_script:
  - cmd: node --version
  - cmd: npm --version
  # - cmd: yarn test
  - cmd: yarn build:windows
  - cmd: if %platform%==x64 yarn build:windows


