image: Visual Studio 2017

matrix:
  fast_finish: true

platform:
  - x86
  - x64

os: unstable

branches:
  only:
    - master
    - release

skip_tags: true

environment:
  nodejs_version: "12"

cache:
  - node_modules -> package.json
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

build_script:
  - cmd: node --version
  - cmd: npm --version
  - cmd: yarn test
  - cmd: npx electron-builder --windows
  # - cmd: if %platform%==x64 npx electron-builder --windows


