name: crossover # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '2.5.5' # just for humans, typically '1.2+git' or '1.3.2'
summary: 🎯 A Crosshair Overlay for any screen. # 79 char long summary
description: |
  CrossOver allows you to place a customizable crosshair overlay above any
  application window. Improve your aim and gain a competitive advantage with
  a permanent colored crosshair to mark center screen.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
